### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by ghost** [shedaniel/slight-gui-modifications#81]
[13:32:14] [Render thread/WARN]: @Redirect conflict. Skipping slight-gui-modifications.mixins.json:MixinTitleScreen from mod slight-gui-modifications->@Redirect::stringRender(Lnet/minecraft/class_4587;Lnet/minecraft/class_327;Ljava/lang/String;III)V with priority 1000, already redirected by essentialclient.mixins.json:core.TitleScreenMixin from mod essential-client->@Redirect::onDrawText(Lnet/minecraft/class_4587;Lnet/minecraft/class_327;Ljava/lang/String;III)V with priority 1000
[13:32:14] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[13:32:14] [Render thread/WARN]: @Redirect conflict. Skipping slight-gui-modifications.mixins.json:MixinTitleScreen from mod slight-gui-modifications->@Redirect::stringRender(Lnet/minecraft/class_4587;Lnet/minecraft/class_327;Ljava/lang/String;III)V with priority 1000, already redirected by essentialclient.mixins.json:core.TitleScreenMixin from mod essential-client->@Redirect::onDrawText(Lnet/minecraft/class_4587;Lnet/minecraft/class_327;Ljava/lang/String;III)V with priority 1000
[13:32:14] [Render thread/ERROR]: Minecraft has crashed!

net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_442 failed
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_442 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:207) ~[fabric-loader-0.14.8-1.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:207) ~[fabric-loader-0.14.8-1.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector stringRender(Lnet/minecraft/class_4587;Lnet/minecraft/class_327;Ljava/lang/String;III)V in slight-gui-modifications.mixins.json:MixinTitleScreen from mod slight-gui-modifications failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap slight-gui-modifications-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:207) ~[fabric-loader-0.14.8-1.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more

**Comment by rayzchen** [comment]
Same issue on 1.19.2

**Comment by SamLolo** [comment]
I get a similar issue on 1.19.2 as well, can't figure out whats causing it

**Comment by jiesou** [comment]
This mod may not support versions above 1.19 at all

**Comment by jiesou** [comment]
GUYS, I spent the night and barely ported to 1.19.2. The approach is rather simple and brutal, just delete the problematic parts
jar download: <http://ctpan.jiecs.top/f/32856022-651562032-afa382>
**The chat box animation is not there now**, everything else should be fine

Original Chinese: 
我搞了一晚上，勉强移植到了 1.19.2。办法比较简单粗暴，直接把有问题的部分删了
jar下载：<http://ctpan.jiecs.top/f/32856022-651562032-afa382>
目前就聊天框动画没有，别的应该没问题

**Comment by ghost** [comment]
Awesome, thanks for your hard work @jiesou 🥰🙏🏿
I will check this later out and tell you if it works.

**Comment by shedaniel** [comment]
Please DO NOT share arbitrary jars, submit a pull request if you can, otherwise don’t share it.

This is for user’s security, you don’t download random executables from randoms online.

**Comment by jiesou** [comment]
Sorry I didn't think about it, the content I uploaded is safe

**Comment by jiesou** [comment]
I just deleted [here](https://github.com/shedaniel/slight-gui-modifications/blob/1.19/src/main/java/me/shedaniel/slightguimodifications/mixin/MixinChatScreen.java#L42-L45) and `modmenu.MixinModListWidget`, `modmenu.MixinModsScreen` in [here](https://github.com/shedaniel/slight-gui-modifications/blob/1.19/src/main/resources/slight-gui-modifications.mixins.json#L11) for temporary use

**Comment by ghost** [comment]
Can I contact you somehow @jiesou and you send me the file please?
Maybe Discord, temporary.

**Comment by ghost** [comment]
Thank you!

**Comment by Technici4n** [comment]
Hi, would you mind backporting the fix to 1.18.2? Thanks

**Comment by rayzchen** [comment]
Same thing for 1.19, I'm on a server which isn't 1.19.2 yet but I would
love to use this mod.

**Comment by ghost** [comment]
Hello @Technici4n and @rayzchen - maybe one of you opens a new issue and link it to this issue #81.
Greetings.
