### ISSUE TITLE
Crashes with FancyMenu

### ISSUE THREAD

**Issue by Madis0** [shedaniel/slight-gui-modifications#9]
Seems like the other mods work fine together, only 'Slight' Gui Modifications makes it crash :(

<details>

```
---- Minecraft Crash Report ----
// Sorry :(

Time: 2020-11-08 12:50:47 EET
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
    at Not Enough Crashes deobfuscated stack trace.(1.16+build.1)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
    at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
    at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:533)
    at net.minecraft.client.main.Main.main(Main:177)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:564)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [slight-gui-modifications.mixins.json:MixinGameRenderer] from phase [DEFAULT] in config [slight-gui-modifications.mixins.json] FAILED during APPLY
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
    ... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 1 for @ModifyArg is invalid for args (Lnet/minecraft/class_437;Lnet/minecraft/class_4587;IIF), expected I on net/minecraft/class_757::transformScreenRenderMouseY [INJECT Applicator Phase -> slight-gui-modifications.mixins.json:MixinGameRenderer -> Apply Injections ->  -> Inject -> slight-gui-modifications.mixins.json:MixinGameRenderer->@ModifyArg::transformScreenRenderMouseY(I)I]
    at Not Enough Crashes deobfuscated stack trace.(1.16+build.1)
    at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:157)
    at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:112)
    at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82)
    at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:102)
    at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
    at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
    ... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Linux (amd64) version 5.8.18-1-MANJARO
  Java Version: 14.0.2, N/A
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 244988752 bytes (233 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
  CPUs: 8
  JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Fabric Loader (fabricloader)
  Fabric Mods: advancementinfo: AdvancementInfo 1.16.2-fabric0.17.2-1.1.1
               amecs: Amecs 1.3.2+mc.1.16.3
               amecsapi: Amecs API 1.1.1+mc1.16-rc1
               antighost: AntiGhost 1.16.2-fabric0.17.2-1.1.3
               appleskin: AppleSkin 1.0.11
               artifice: Artifice 0.13.1+1.16.2-rc1
               autoconfig1u: Auto Config v1 Updated 3.3.1
               autofish: Autofish 0.9.0
               autoharvest: autoharvest 1.0.5
               bedrockify: BedrockIfy 0.1.9
               beenfo: Beenfo 1.16.3-fabric0.20.2-1.2
               blur: Blur 1.0.6
               capes: Capes 1.1.1
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.9
               cloth-config2: Cloth Config v4 4.8.3
               colormatic: Colormatic 2.2.7+mc.1.16.3
               com_moandjiezana_toml_toml4j: toml4j 0.7.2
               com_squareup_moshi_moshi: moshi 1.9.2
               com_squareup_okio_okio: okio 1.16.0
               cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
               crowdin-translate: CrowdinTranslate 1.1
               custom-fog: Custom Fog 1.2.0
               dynamicfps: Dynamic FPS 1.2.1
               fabric: Fabric API 0.25.4+1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893a
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db23a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5fa7
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a3a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a3a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db23a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db23a
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db23a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf3a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+c93221003a
               fabricloader: Fabric Loader 0.10.6+build.214
               fancymenu: FancyMenu 1.5.4
               fiber: fiber 0.23.0-2
               gbfabrictools: GBfabrictools 1.2.2+1.16.2
               grass_kiss: Grass Kiss 0.2.2-custom
               horseinfo: Horse Info 0.2.2-1.16.1
               konkrete: Konkrete 1.0.4
               lambdynlights: LambDynamicLights 1.3.2+1.16.4
               lithium: Lithium 0.5.6-SNAPSHOT
               lithium-api: Lithium API 0.5.6-SNAPSHOT
               loadcatcher: Entrypoint Catcher 2.0.0
               minecraft: Minecraft 1.16.4
               mm: Manningham Mills 2.1
               modmenu: Mod Menu 1.14.6+build.31
               modupdater: ModUpdater 1.1.11+1.16.2-rc2
               mousewheelie: Mouse Wheelie 1.5.9+mc1.16.4
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               okzoomer: Ok Zoomer 4.0.1+1.16.2
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               org_yaml_snakeyaml: snakeyaml 1.26
               phosphor: Phosphor 0.6.0-SNAPSHOT
               recipeunlocker: RecipeUnlocker 1.15-fabric0.4.23-1.5
               roughlyenoughitems: Roughly Enough Items 5.8.2
               roughlyenoughitems-api: REI (API) 5.8.2
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.2
               roughlyenoughitems-runtime: REI (Runtime) 5.8.2
               satin: Satin 1.4.1
               sectionsign: SectionSign 1.0.2
               shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
               slight-gui-modifications: 'Slight' GUI Modifications 1.5.1
               smoothboot: Smooth Boot 1.1.0
               smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
               sodium: Sodium 0.1.0
               spruceui: SpruceUI 1.6.4
               toomanybinds: Too Many Binds 0.3.0+1.16.3
               tweed: Tweed API 3.0.0-beta.18
               viafabric: ViaFabric 0.2.16-SNAPSHOT+build-586.1-mc-1.16
               viaversion: ViaVersion 3.2.0
               voxelmap: VoxelMap 1.10.11
               waila: Hwyla 1.9.22
  Launched Version: fabric-loader-0.10.6+build.214-1.16.4
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: Mesa Intel(R) Iris(R) Plus Graphics (ICL GT2) GL version 4.6 (Compatibility Profile) Mesa 20.2.1, Intel
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: 8x Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz

```

</details>

**Comment by shedaniel** [comment]
SGM is inherently incompatible with FancyMenu as we both provide custom title screen.

**Comment by Madis0** [comment]
What if the groovy file is removed and options related to title screen are disabled (e.g unlimit FPS)?
