### ISSUE TITLE
Generates spam logs continuously when used with Sodium Extra 0.4.24 and above.

### ISSUE THREAD

**Issue by LittleCircleOO** [shedaniel/slight-gui-modifications#99]
### Version
Minecraft 1.20.1
Fabric Loader 0.14.21
Fabric Api 0.86.1
**Slight Gui Modifications 2.6.1**
Sodium 0.4.10 build.27
**Sodium Extra 0.4.24 and above**
### Description
When I updated **Sodium Extra** to version **0.4.24 and above**, the following error message was repeatedly scrubbed from the logs, which resulted in disk space being quickly overwritten with garbage messages. The error message points to this mod.
```
[Render thread/INFO]: [STDERR]: java.lang.IllegalStateException
[Render thread/INFO]: [STDERR]: 	at me.shedaniel.slightguimodifications.SlightGuiModifications.setAlpha(SlightGuiModifications.java:86)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_332.handler$jfd000$slight-gui-modifications$innerBlit(class_332.java:5777)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_332.method_25295(class_332.java)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_332.method_25298(class_332.java:309)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_485.method_18643(class_485.java:96)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_485.method_2477(class_485.java:57)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_485.method_25394(class_485.java:28)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_490.method_25394(class_490.java:88)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_47413(class_437.java:110)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:945)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1219)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:802)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:250)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[Render thread/INFO]: [STDERR]: 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
[Render thread/INFO]: [STDERR]: 	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
```

**Comment by LittleCircleOO** [comment]
Related to https://github.com/FlashyReese/sodium-extra-fabric/issues/340
